name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch: # Allow manual trigger from Github UI
  push:
    branches:
      - main  # Or 'master', depending on your default branch

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        run: echo "COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build with parcel
        run: |
          npm run build
          touch dist/.nojekyll
        env:
          NODE_ENV: production

      - name: Add commit info page
        run: |
          echo "<!DOCTYPE html><html><body>" > dist/commit.html
          echo "<p>Built from commit <a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>__COMMIT_ID__</a></p>" >> dist/commit.html
          echo "</body></html>" >> dist/commit.html
          
      - name: Inject commit into HTML files
        run: |
          ind dist -type f -name "*.html" -exec sed -i "s|__COMMIT_ID__|<a href='https://github.com/${{ github.repository }}/commit/${{ github.sha }}'>${{ env.COMMIT_ID }}</a>|g" {} +
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

