name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch: # Allow manual trigger from Github UI
  push:
    branches:
      - main  # Or 'master', depending on your default branch

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build with parcel
        run: |
          npm run build
          touch dist/.nojekyll
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

